# Generated by Django 4.2.7 on 2023-12-02 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_num', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(max_length=255)),
                ('Account_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_code', models.CharField(max_length=255)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_description', models.TextField()),
                ('category_created', models.DateTimeField()),
                ('category_image', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.PositiveIntegerField()),
                ('gst_no', models.CharField(max_length=9)),
                ('sale_datetime', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('number_of_products', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sgst_amount', models.CharField(max_length=20)),
                ('cgst_amount', models.CharField(max_length=20)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_giving_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_given_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_type', models.CharField(default='Cash', max_length=20)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Sales_Product',
            fields=[
                ('sales_products_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.PositiveIntegerField()),
                ('gst_no', models.CharField(max_length=9)),
                ('sale_datetime', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('customer_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('hns_code', models.CharField(max_length=9)),
                ('quantity', models.PositiveIntegerField()),
                ('sale_product_datetime', models.DateTimeField()),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Sales_product',
                'verbose_name_plural': 'Sales_product',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_name', models.CharField(default=100000000, max_length=255)),
                ('phone_num', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gst_num', models.PositiveIntegerField()),
                ('invoice_num', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchases_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=25)),
                ('quantity', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(max_length=2000)),
                ('gst', models.CharField(max_length=8)),
                ('discount', models.CharField(max_length=8)),
                ('hsn_code', models.CharField(max_length=30)),
                ('mrp', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='Active', max_length=30)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('purchase_created', models.DateTimeField()),
                ('total_amount', models.FloatField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_category', to='product.category', to_field='category_name')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vendor', to='product.vendor')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=25)),
                ('quantity', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(max_length=2000)),
                ('gst', models.CharField(max_length=8)),
                ('discount', models.CharField(max_length=8)),
                ('hsn_code', models.CharField(max_length=30)),
                ('mrp', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='Active', max_length=30)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('product_created', models.DateTimeField()),
                ('product_modified', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='product.category', to_field='category_name')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='product.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
