# Generated by Django 4.2.7 on 2023-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_product',
            name='bill_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sales_product',
            name='cgst_amount',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='sales_product',
            name='sgst_amount',
            field=models.CharField(max_length=9),
        ),
    ]
